import {
  AccountChoice,
  Audit,
  Confirm,
  ConnectionRow,
  Field,
  Navigation,
  PermissionChoice,
  SecurityMethods,
  SessionRow,
  ActionLink,
  Brand,
  Button,
  Empty,
  Failure,
  LandingHero,
  Loading,
  Notice,
  PageTitle,
  SiteShell,
} from "./components.mjs";

function document(title, body, script = "") {
  return `<!doctype html>
<!-- Generated by scripts/build-identity-template.mjs. Edit specimen.mjs/components.mjs. -->
<html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#eaf1ec"><title>${title}</title><link rel="preload" href="fonts/bricolage-grotesque-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="fonts/instrument-sans-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="product.css"><link rel="stylesheet" href="specimen.css"></head><body>${body}${script}</body></html>\n`;
}

function navigation(page) {
  return Navigation({
    label: "Voorbeelden",
    currentHref: `${page}.html`,
    items: [
      { href: "index.html", label: "Aankomst" },
      { href: "states.html", label: "Meldingen" },
      { href: "account.html", label: "Keuzes" },
    ],
  });
}

const footerHtml = `${Brand({ href: "index.html" })}<span>Ontwerptemplate. Geen gekoppeld account.</span>`;

export function landingDocument() {
  const contentHtml =
    LandingHero({
      eyebrow: "Jouw ChefGroep-account",
      titleLines: ["Jouw plek", "binnen"],
      emphasis: "ChefGroep.",
      description:
        "Je account, sessies en verbindingen op één plek. Jij bepaalt welke apps toegang krijgen.",
      actionsHtml: ActionLink({
        href: "#decision",
        label: "Bekijk het toegangspatroon",
      }),
    }) +
    `<section id="decision" class="template-note"><p class="eyebrow">Herbruikbaar patroon</p><h2>Een herkenbare aankomst.<br>Een duidelijke beslissing.</h2><p>Dit is een ontwerptemplate, geen gekoppeld account. De productimplementatie toont hier de echte client, dienst, accountkeuze en gevraagde rechten. Toestemming en intrekking worden uitsluitend bevestigd na een geslaagde servermutatie.</p><p><a href="states.html">Bekijk laad-, leeg- en foutmeldingen</a></p><p><a href="../../reports/chefgroep-auth-2026-09-12/index.html">Lees de volledige ontwerpevaluatie</a></p></section>`;
  return document(
    "ChefGroep identity · ontwerptemplate",
    SiteShell({
      contentHtml,
      plane: "Ontwerptemplate",
      navigationHtml: navigation("index"),
      footerHtml,
      homeHref: "index.html",
    }),
  );
}

export function stateMarkup(kind, interactive = true) {
  switch (kind) {
    case "loading":
      return Loading({ message: "Voorbeeld: gegevens worden opgehaald." });
    case "empty":
      return Empty({
        title: "Voorbeeld: geen verbindingen.",
        message:
          "Een product toont hier wat je kunt doen wanneer er nog geen verbindingen zijn.",
        actionHtml: ActionLink({
          href: "index.html",
          label: "Terug naar het aankomstvoorbeeld",
          secondary: true,
        }),
      });
    case "error":
      return Failure({
        title: "Voorbeeld: ophalen mislukt.",
        message:
          "Deze demonstratie verstuurt geen verzoek. Opnieuw proberen toont de laadmelding.",
        actionHtml: Button({
          id: "retry",
          label: "Opnieuw proberen",
          intent: "neutral",
          disabled: !interactive,
        }),
      });
    case "notice":
      return Notice({
        message:
          "Voorbeeldmelding. Een echt product bevestigt een wijziging pas na een geslaagde servermutatie.",
      });
    default:
      throw new TypeError("Unknown specimen state");
  }
}

export function statesDocument() {
  const contentHtml = `<section class="template-note">${PageTitle({ eyebrow: "Ontwerptemplate", title: "Heldere meldingen.", description: "Bekijk hoe dezelfde productwereld reageert op laden, afwezigheid en fouten. Dit voorbeeld heeft geen account of API-verbinding." })}
    <fieldset class="state-selector" disabled><legend>Kies een voorbeeldmelding</legend>${[
      ["loading", "Laden"],
      ["empty", "Leeg"],
      ["error", "Fout"],
      ["notice", "Melding"],
    ]
      .map(
        ([value, label]) =>
          `<label><input type="radio" name="example-state" value="${value}"${value === "error" ? " checked" : ""}> ${label}</label>`,
      )
      .join("")}</fieldset>
    <div id="state-example">${stateMarkup("error", false)}</div>
    <noscript><p>De voorbeeldkeuze werkt met JavaScript. De foutmelding hierboven blijft leesbaar.</p></noscript>
  </section>`;
  return document(
    "ChefGroep identity · meldingen",
    SiteShell({
      contentHtml,
      plane: "Ontwerptemplate",
      navigationHtml: navigation("states"),
      footerHtml,
      homeHref: "index.html",
    }),
    '<script type="module" src="states.mjs"></script>',
  );
}

export function accountDocument() {
  const fields = Field({
    id: "example-name",
    name: "displayName",
    label: "Voorbeeldnaam",
    autocomplete: "nickname",
    hint: "Gebruik alleen voorbeeldgegevens.",
    required: true,
    error: "Vul een voorbeeldnaam in om de validatiefocus te bekijken.",
  });
  const accounts = AccountChoice({
    id: "accounts",
    name: "account",
    legend: "Kies een voorbeeldaccount",
    selectedValue: "example-a",
    options: [
      {
        value: "example-a",
        label: "Voorbeeldaccount A",
        description: "Kiesbaar volgens de aangeleverde voorbeeldstatus.",
        membership: "eligible",
      },
      {
        value: "example-b",
        label: "Voorbeeldaccount B",
        description: "Voorbeeld van ontbrekende toegang.",
        membership: "ineligible",
        unavailableReason:
          "Dit voorbeeldaccount heeft geen toegang tot deze dienst.",
      },
    ],
  });
  const permissions = PermissionChoice({
    id: "permissions",
    name: "scope",
    legend: "Gevraagde voorbeeldrechten",
    permissions: [
      {
        value: "example:read",
        label: "Voorbeeldprofiel bekijken",
        description: "Een vereist recht blijft zichtbaar en geselecteerd.",
        required: true,
      },
      {
        value: "example:write",
        label: "Voorbeeldprofiel wijzigen",
        description: "Dit optionele recht kun je zelf selecteren.",
        required: false,
        checked: false,
      },
    ],
  });
  const connections = [
    ConnectionRow({
      id: "example-connection",
      name: "Voorbeeldverbinding",
      description:
        "Alle rijen op deze pagina zijn ontwerpficties, geen live toegang.",
      state: "active",
      actionId: "connection-revoke",
    }),
    ConnectionRow({
      id: "expired-connection",
      name: "Verlopen voorbeeld",
      description: "De aangeleverde status is verlopen.",
      state: "expired",
    }),
    ConnectionRow({
      id: "revoked-connection",
      name: "Ingetrokken voorbeeld",
      description: "De aangeleverde status is ingetrokken.",
      state: "revoked",
    }),
    ConnectionRow({
      id: "pending-connection",
      name: "Voorbeeld tijdens intrekken",
      description:
        "De actieve status blijft staan tot de consumer een resultaat bevestigt.",
      state: "active",
      actionId: "pending-revoke",
      pending: true,
    }),
    ConnectionRow({
      id: "failed-connection",
      name: "Voorbeeld na een fout",
      description: "Een mislukte poging wordt geen geslaagde intrekking.",
      state: "active",
      error: "Voorbeeldfout: de intrekking is niet bevestigd.",
    }),
  ].join("");
  const sessions = [
    SessionRow({
      id: "current-session",
      name: "Voorbeeld van dit apparaat",
      description: "De consumer levert de huidige-apparaatstatus aan.",
      current: true,
      consequence: "Beëindigen meldt dit voorbeeldapparaat af.",
      actionId: "session-revoke",
    }),
    SessionRow({
      id: "other-session",
      name: "Voorbeeld van een ander apparaat",
      description: "Geen apparaatgegevens worden uit de browser afgeleid.",
      consequence: "Beëindigen meldt het andere apparaat af.",
      pending: true,
      actionId: "pending-session",
    }),
  ].join("");
  const contentHtml = `<section class="template-note">${PageTitle({ eyebrow: "Ontwerptemplate", title: "Bewuste keuzes.", description: "Voorbeeldgegevens laten accountkeuze, rechten en herstel zien. Deze pagina heeft geen account, API of echte mutaties." })}
    <form id="example-form" novalidate>${fields}${accounts}${permissions}${Button({ label: "Bekijk validatiefocus", id: "validate-example", intent: "neutral", disabled: true })}<p id="validation-result" role="status"></p></form>
    <section class="identity-section"><h2>Voorbeeldverbindingen</h2><ul class="identity-rows">${connections.replace('id="connection-revoke"', 'id="connection-revoke" disabled')}</ul></section>
    <section class="identity-section"><h2>Voorbeeldsessies</h2><ul class="identity-rows">${sessions.replace('id="session-revoke"', 'id="session-revoke" disabled')}</ul></section>
    <section class="identity-section"><h2>Voorbeeld van aanmeldmethoden</h2>${SecurityMethods({ state: "ready", methods: [{ label: "Voorbeeldmethode", description: "Een consumer geeft hier de werkelijk ingestelde methode door." }] })}${SecurityMethods({ state: "unavailable", message: "Voorbeeld: de upstream kan geen methoden leveren." })}</section>
    <section class="identity-section"><h2>Voorbeeld van een gebeurtenissenlijst</h2><p>De volgende gebeurtenis is een vaste ontwerpfictie.</p>${Audit({ events: [{ actor: "Voorbeeldgebruiker", action: "Voorbeeld van een gewijzigde verbinding", timestamp: "2026-09-11T12:00:00Z" }] })}</section>
  </section>${Confirm({ id: "connection-confirm", title: "Voorbeeldverbinding intrekken?", message: "Dit voorbeeld simuleert een mislukte intrekking. Er wordt niets verstuurd of gewijzigd.", actionLabel: "Intrekken" })}${Confirm({ id: "session-confirm", title: "Voorbeeldsessie beëindigen?", message: "Dit voorbeeld simuleert een fout. In een product beëindigt deze actie de geselecteerde sessie.", actionLabel: "Sessie beëindigen" })}`;
  return document(
    "ChefGroep identity · keuzes",
    SiteShell({
      contentHtml,
      plane: "Ontwerptemplate",
      navigationHtml: navigation("account"),
      footerHtml,
      homeHref: "index.html",
    }),
    '<script type="module" src="account.mjs"></script>',
  );
}
