import {
  ActionLink,
  Brand,
  Button,
  Empty,
  Failure,
  LandingHero,
  Loading,
  Notice,
  PageTitle,
  SiteShell,
} from "./components.mjs";

function document(title, body, script = "") {
  return `<!doctype html>
<!-- Generated by scripts/build-identity-template.mjs. Edit specimen.mjs/components.mjs. -->
<html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#eaf1ec"><title>${title}</title><link rel="preload" href="fonts/bricolage-grotesque-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="fonts/instrument-sans-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="product.css"><link rel="stylesheet" href="specimen.css"></head><body>${body}${script}</body></html>\n`;
}

function navigation(page) {
  return `<nav aria-label="Voorbeelden">${[
    ["index", "Aankomst"],
    ["states", "Meldingen"],
  ]
    .map(
      ([path, label]) =>
        `<a href="${path}.html"${path === page ? ' aria-current="page" class="active"' : ""}>${label}</a>`,
    )
    .join("")}</nav>`;
}
const footerHtml = `${Brand({ href: "index.html" })}<span>Ontwerptemplate. Geen gekoppeld account.</span>`;

export function landingDocument() {
  const contentHtml =
    LandingHero({
      eyebrow: "Jouw ChefGroep-account",
      titleLines: ["Jouw plek", "binnen"],
      emphasis: "ChefGroep.",
      description:
        "Je account, sessies en verbindingen op één plek. Jij bepaalt welke apps toegang krijgen.",
      actionsHtml: ActionLink({
        href: "#decision",
        label: "Bekijk het toegangspatroon",
      }),
    }) +
    `<section id="decision" class="template-note"><p class="eyebrow">Herbruikbaar patroon</p><h2>Een herkenbare aankomst.<br>Een duidelijke beslissing.</h2><p>Dit is een ontwerptemplate, geen gekoppeld account. De productimplementatie toont hier de echte client, dienst, accountkeuze en gevraagde rechten. Toestemming en intrekking worden uitsluitend bevestigd na een geslaagde servermutatie.</p><p><a href="states.html">Bekijk laad-, leeg- en foutmeldingen</a></p><p><a href="../../reports/chefgroep-auth-2026-09-12/index.html">Lees de volledige ontwerpevaluatie</a></p></section>`;
  return document(
    "ChefGroep identity · ontwerptemplate",
    SiteShell({
      contentHtml,
      plane: "Ontwerptemplate",
      navigationHtml: navigation("index"),
      footerHtml,
      homeHref: "index.html",
    }),
  );
}

export function stateMarkup(kind, interactive = true) {
  switch (kind) {
    case "loading":
      return Loading({ message: "Voorbeeld: gegevens worden opgehaald." });
    case "empty":
      return Empty({
        title: "Voorbeeld: geen verbindingen.",
        message:
          "Een product toont hier wat je kunt doen wanneer er nog geen verbindingen zijn.",
        actionHtml: ActionLink({
          href: "index.html",
          label: "Terug naar het aankomstvoorbeeld",
          secondary: true,
        }),
      });
    case "error":
      return Failure({
        title: "Voorbeeld: ophalen mislukt.",
        message:
          "Deze demonstratie verstuurt geen verzoek. Opnieuw proberen toont de laadmelding.",
        actionHtml: Button({
          id: "retry",
          label: "Opnieuw proberen",
          intent: "neutral",
          disabled: !interactive,
        }),
      });
    case "notice":
      return Notice({
        message:
          "Voorbeeldmelding. Een echt product bevestigt een wijziging pas na een geslaagde servermutatie.",
      });
    default:
      throw new TypeError("Unknown specimen state");
  }
}

export function statesDocument() {
  const contentHtml = `<section class="template-note">${PageTitle({ eyebrow: "Ontwerptemplate", title: "Heldere meldingen.", description: "Bekijk hoe dezelfde productwereld reageert op laden, afwezigheid en fouten. Dit voorbeeld heeft geen account of API-verbinding." })}
    <fieldset class="state-selector" disabled><legend>Kies een voorbeeldmelding</legend>${[
      ["loading", "Laden"],
      ["empty", "Leeg"],
      ["error", "Fout"],
      ["notice", "Melding"],
    ]
      .map(
        ([value, label]) =>
          `<label><input type="radio" name="example-state" value="${value}"${value === "error" ? " checked" : ""}> ${label}</label>`,
      )
      .join("")}</fieldset>
    <div id="state-example">${stateMarkup("error", false)}</div>
    <noscript><p>De voorbeeldkeuze werkt met JavaScript. De foutmelding hierboven blijft leesbaar.</p></noscript>
  </section>`;
  return document(
    "ChefGroep identity · meldingen",
    SiteShell({
      contentHtml,
      plane: "Ontwerptemplate",
      navigationHtml: navigation("states"),
      footerHtml,
      homeHref: "index.html",
    }),
    '<script type="module" src="states.mjs"></script>',
  );
}
