#!/usr/bin/env python3
"""Generate runtime distribution artifacts from the canonical Signaal tokens.css."""
from __future__ import annotations
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tokens.css"
OUT = ROOT / "packages" / "tokens"
VAR = re.compile(r"--([a-zA-Z0-9-]+)\s*:\s*([^;]+);")

def block(selector: str, text: str) -> dict[str, str]:
    marker = selector + " {"
    start = text.index(marker) + len(marker)
    depth = 1
    i = start
    while i < len(text) and depth:
        if text[i] == "{": depth += 1
        elif text[i] == "}": depth -= 1
        i += 1
    return {k: v.strip() for k, v in VAR.findall(text[start:i-1])}

def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    light = block(":root", text)
    dark = block('[data-theme="dark"]', text)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "tokens.css").write_text(text, encoding="utf-8")
    js = "// Generated by scripts/build-runtime-packages.py. Do not edit.\n" + \
         "export const light = Object.freeze(" + json.dumps(light, indent=2) + ");\n" + \
         "export const dark = Object.freeze(" + json.dumps(dark, indent=2) + ");\n" + \
         "export const themes = Object.freeze({ light, dark });\n"
    (OUT / "index.js").write_text(js, encoding="utf-8")
    (OUT / "index.d.ts").write_text(
        "export declare const light: Readonly<Record<string, string>>;\n"
        "export declare const dark: Readonly<Record<string, string>>;\n"
        "export declare const themes: Readonly<{ light: typeof light; dark: typeof dark }>;\n",
        encoding="utf-8",
    )
if __name__ == "__main__": main()
