import * as React from "react";
export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "default"|"primary"|"subtle"|"outline"|"ghost"|"destructive"; size?: "sm"|"md"|"lg"; pending?: boolean };
export const Button: React.ForwardRefExoticComponent<ButtonProps & React.RefAttributes<HTMLButtonElement>>;
export type IconButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { label: string; variant?: "ghost"|"outline"|"solid"; pending?: boolean };
export const IconButton: React.ForwardRefExoticComponent<IconButtonProps & React.RefAttributes<HTMLButtonElement>>;
export type BadgeProps = React.HTMLAttributes<HTMLSpanElement> & { tone?: "neutral"|"accent"|"success"|"warning"|"danger" };
export const Badge: React.ForwardRefExoticComponent<BadgeProps & React.RefAttributes<HTMLSpanElement>>;
export const Input: React.ForwardRefExoticComponent<React.InputHTMLAttributes<HTMLInputElement> & React.RefAttributes<HTMLInputElement>>;
export const Textarea: React.ForwardRefExoticComponent<React.TextareaHTMLAttributes<HTMLTextAreaElement> & React.RefAttributes<HTMLTextAreaElement>>;
export const Select: React.ForwardRefExoticComponent<React.SelectHTMLAttributes<HTMLSelectElement> & React.RefAttributes<HTMLSelectElement>>;
export const InputGroup: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>>;
export const InputAffix: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLSpanElement> & React.RefAttributes<HTMLSpanElement>>;
export type ChoiceProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, "type"> & { label: React.ReactNode; description?: React.ReactNode; inputClassName?: string };
export const Checkbox: React.ForwardRefExoticComponent<ChoiceProps & React.RefAttributes<HTMLInputElement>>;
export const Radio: React.ForwardRefExoticComponent<ChoiceProps & React.RefAttributes<HTMLInputElement>>;
export type SwitchProps = Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onChange"> & { checked?: boolean; onCheckedChange?: (checked: boolean) => void };
export const Switch: React.ForwardRefExoticComponent<SwitchProps & React.RefAttributes<HTMLButtonElement>>;
export function Field(props: React.HTMLAttributes<HTMLDivElement> & { label?: React.ReactNode; htmlFor?: string; help?: React.ReactNode; error?: React.ReactNode; required?: boolean; layout?: "stacked"|"inline"; children: React.ReactNode }): React.ReactElement;
export const Separator: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLDivElement> & { orientation?: "horizontal"|"vertical" } & React.RefAttributes<HTMLDivElement>>;
export function Alert(props: React.HTMLAttributes<HTMLDivElement> & { tone?: "neutral"|"accent"|"success"|"warning"|"danger" }): React.ReactElement;
export function EmptyState(props: React.HTMLAttributes<HTMLElement> & { title: React.ReactNode; description?: React.ReactNode; action?: React.ReactNode }): React.ReactElement;
export function Activity(props: React.HTMLAttributes<HTMLDivElement> & { state?: "idle"|"running"|"waiting"|"complete"|"error"; label: React.ReactNode; detail?: React.ReactNode; elapsed?: React.ReactNode }): React.ReactElement;

export type MotionKind = "beam"|"halo"|"sweep"|"ripple"|"glide"|"status";
export type MotionSurfaceProps = React.HTMLAttributes<HTMLElement> & { as?: React.ElementType; motion?: MotionKind; active?: boolean };
export const MotionSurface: React.ForwardRefExoticComponent<MotionSurfaceProps & React.RefAttributes<HTMLElement>>;
export function attachPressRipple(element: HTMLElement | null): () => void;

export const Dialog: React.ForwardRefExoticComponent<React.DialogHTMLAttributes<HTMLDialogElement> & React.RefAttributes<HTMLDialogElement>>;
export type SheetProps = React.DialogHTMLAttributes<HTMLDialogElement> & { side?: "left"|"right" };
export const Sheet: React.ForwardRefExoticComponent<SheetProps & React.RefAttributes<HTMLDialogElement>>;
export type PopoverProps = React.HTMLAttributes<HTMLDivElement> & { popover?: "auto"|"manual"|"" };
export const Popover: React.ForwardRefExoticComponent<PopoverProps & React.RefAttributes<HTMLDivElement>>;
export const Menu: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>>;
export type MenuItemProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { tone?: "default"|"danger" };
export const MenuItem: React.ForwardRefExoticComponent<MenuItemProps & React.RefAttributes<HTMLButtonElement>>;
export const Tooltip: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLSpanElement> & React.RefAttributes<HTMLSpanElement>>;
export type TabListProps = React.HTMLAttributes<HTMLDivElement> & { variant?: "line"|"segmented" };
export const TabList: React.ForwardRefExoticComponent<TabListProps & React.RefAttributes<HTMLDivElement>>;
export type TabProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { selected?: boolean };
export const Tab: React.ForwardRefExoticComponent<TabProps & React.RefAttributes<HTMLButtonElement>>;
export type BreadcrumbProps = React.HTMLAttributes<HTMLElement> & { label?: string };
export const Breadcrumb: React.ForwardRefExoticComponent<BreadcrumbProps & React.RefAttributes<HTMLElement>>;
export type PaginationProps = React.HTMLAttributes<HTMLElement> & { label?: string };
export const Pagination: React.ForwardRefExoticComponent<PaginationProps & React.RefAttributes<HTMLElement>>;
export type ToastProps = React.HTMLAttributes<HTMLDivElement> & { live?: "off"|"polite"|"assertive" };
export const Toast: React.ForwardRefExoticComponent<ToastProps & React.RefAttributes<HTMLDivElement>>;
export const Progress: React.ForwardRefExoticComponent<React.ProgressHTMLAttributes<HTMLProgressElement> & React.RefAttributes<HTMLProgressElement>>;
export type SkeletonProps = React.HTMLAttributes<HTMLDivElement> & { width?: React.CSSProperties["width"]; height?: React.CSSProperties["height"] };
export const Skeleton: React.ForwardRefExoticComponent<SkeletonProps & React.RefAttributes<HTMLDivElement>>;
